# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='amount',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 11, 30, 14, 55, 9, 752627, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
