# Generated by Django 2.0 on 2017-12-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Comment', max_length=200),
        ),
    ]
